package com.datacentre.model.pojo;
// Generated 17.09.2016 21:33:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistrationCard generated by hbm2java
 */
@Entity
@Table(name="registration_card"
    ,catalog="medicalDB"
)

public class RegistrationCard  implements java.io.Serializable {
     private String mobile;
     private String fullName;
     private int age;
     private Date dateRegistration;

    public RegistrationCard() {
    }

    public RegistrationCard(String mobile, String fullName, int age, Date dateRegistration) {
       this.mobile = mobile;
       this.fullName = fullName;
       this.age = age;
       this.dateRegistration = dateRegistration;
    }
   
     @Id 

    
    @Column(name="mobile", unique=true, nullable=false, length=10)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="full_name", nullable=false, length=100)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="age", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_registration", nullable=false, length=19)
    public Date getDateRegistration() {
        return this.dateRegistration;
    }
    
    public void setDateRegistration(Date dateRegistration) {
        this.dateRegistration = dateRegistration;
    }

}


